# Generated by Django 4.2.3 on 2023-08-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=70)),
                ('job_description', models.TextField()),
                ('company', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('publish_date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
    ]
