# Generated by Django 4.2.3 on 2023-08-15 00:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userProfile',
            new_name='Profile',
        ),
    ]
