# Generated by Django 4.2.3 on 2023-08-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_profile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='profilePics'),
        ),
    ]
