# Generated by Django 4.2.3 on 2023-10-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_jobs_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarships',
            fields=[
                ('scholarship_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('university', models.CharField(max_length=70)),
                ('scholarship_title', models.CharField(max_length=70)),
                ('deadline', models.CharField(max_length=70)),
                ('country', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=15)),
                ('course_start', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=400)),
            ],
        ),
    ]
