# Generated by Django 4.2.3 on 2023-10-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_scholarships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='course_start',
            field=models.CharField(max_length=70),
        ),
    ]
