# Generated by Django 4.2.3 on 2023-10-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_scholarships_course_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='degree',
            field=models.CharField(max_length=30),
        ),
    ]
