# Generated by Django 4.2.3 on 2023-11-11 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_jobs_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['-publish_date'], 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AddField(
            model_name='jobs',
            name='is_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobs',
            name='users_clicked',
            field=models.ManyToManyField(blank=True, related_name='clicked_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobs',
            name='users_saved',
            field=models.ManyToManyField(blank=True, related_name='saved_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClickHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_clicked', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
