# Generated by Django 4.2.3 on 2023-11-15 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_remove_jobs_users_clicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='users_clicked',
            field=models.ManyToManyField(blank=True, related_name='clicked_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
